from __future__ import annotations


FIELD_SPECS: list[tuple[str, str]] = [
    ("snapshot_date", "DATE"),
    ("source", "VARCHAR"),
    ("source_project_id", "VARCHAR"),
    ("project_name", "VARCHAR"),
    ("developer_id", "VARCHAR"),
    ("developer_name", "VARCHAR"),
    ("developer_status", "VARCHAR"),
    ("developer_project_count", "BIGINT"),
    ("developer_license_number", "VARCHAR"),
    ("developer_license_start_date", "DATE"),
    ("developer_license_end_date", "DATE"),
    ("state", "VARCHAR"),
    ("district", "VARCHAR"),
    ("city", "VARCHAR"),
    ("project_location", "VARCHAR"),
    ("latitude", "DOUBLE"),
    ("longitude", "DOUBLE"),
    ("source_state_value", "VARCHAR"),
    ("source_district_value", "VARCHAR"),
    ("source_city_value", "VARCHAR"),
    ("permit_number", "VARCHAR"),
    ("permit_start_date", "DATE"),
    ("permit_end_date", "DATE"),
    ("first_spa_date", "DATE"),
    ("teduh_spa_price_min", "DECIMAL(24,2)"),
    ("teduh_spa_price_max", "DECIMAL(24,2)"),
    ("hims_project_reference_date", "DATE"),
    ("hims_project_reference_date_basis", "VARCHAR"),
    ("hims_eligibility_cutoff_date", "DATE"),
    ("project_status", "VARCHAR"),
    ("development_type", "VARCHAR"),
    ("agreement_type", "VARCHAR"),
    ("original_construction_period", "VARCHAR"),
    ("expected_vp_date", "DATE"),
    ("vp_period_amended", "VARCHAR"),
    ("approved_extension_period", "VARCHAR"),
    ("revised_construction_period", "VARCHAR"),
    ("revised_vp_date", "DATE"),
    ("ccc_obtained", "VARCHAR"),
    ("ccc_date", "DATE"),
    ("vp_date", "DATE"),
    ("reported_total_units", "BIGINT"),
    ("unit_records_count", "BIGINT"),
    ("priced_unit_records_count", "BIGINT"),
    ("sold_units", "BIGINT"),
    ("unsold_units", "BIGINT"),
    ("booked_or_reserved_units", "BIGINT"),
    ("unknown_sales_status_units", "BIGINT"),
    ("comparable_total_units", "BIGINT"),
    ("sales_percentage", "DOUBLE"),
    ("value_sold_percentage", "DOUBLE"),
    ("sales_construction_gap", "DOUBLE"),
    ("construction_percentage", "DOUBLE"),
    ("potential_listed_gdv", "DECIMAL(24,2)"),
    ("sold_listed_value", "DECIMAL(24,2)"),
    ("recorded_spa_sales_value", "DECIMAL(24,2)"),
    ("estimated_sold_value", "DECIMAL(24,2)"),
    ("remaining_listed_value", "DECIMAL(24,2)"),
    ("recorded_price_realisation_percentage", "DOUBLE"),
    ("median_recorded_discount_percentage", "DOUBLE"),
    ("bumi_total_units", "BIGINT"),
    ("bumi_sold_units", "BIGINT"),
    ("bumi_unsold_units", "BIGINT"),
    ("bumi_sales_percentage", "DOUBLE"),
    ("minimum_indicative_gdv", "DECIMAL(24,2)"),
    ("maximum_indicative_gdv", "DECIMAL(24,2)"),
    ("unit_coverage_percentage", "DOUBLE"),
    ("listed_price_coverage_percentage", "DOUBLE"),
    ("spa_price_coverage_percentage", "DOUBLE"),
    ("duplicate_unit_identifiers", "BIGINT"),
    ("construction_row_units", "BIGINT"),
    ("construction_row_count", "BIGINT"),
    ("gdv_confidence", "VARCHAR"),
    ("sales_percentage_confidence", "VARCHAR"),
    ("sales_value_confidence", "VARCHAR"),
    ("construction_confidence", "VARCHAR"),
    ("construction_note", "VARCHAR"),
    ("component_sales_count", "BIGINT"),
    ("component_sales_confidence", "VARCHAR"),
    ("component_sales_note", "VARCHAR"),
    ("source_url", "VARCHAR"),
    ("source_detail_api_url", "VARCHAR"),
    ("source_units_api_url", "VARCHAR"),
    ("source_dataset_as_of", "DATE"),
    ("source_dataset_as_of_method", "VARCHAR"),
    ("retrieved_at", "VARCHAR"),
    ("transformation_version", "VARCHAR"),
    ("construction_rows_json", "VARCHAR"),
    ("component_sales_json", "VARCHAR"),
    ("remaining_inventory_json", "VARCHAR"),
    ("permit_history_json", "VARCHAR"),
]
FIELDS = [name for name, _ in FIELD_SPECS]


VALIDATION_FIELDS = [
    "selection_role",
    "source_project_id",
    "project_name",
    "developer_id",
    "developer_name",
    "developer_status",
    "developer_license_end_date",
    "snapshot_date",
    "source_dataset_as_of",
    "project_status",
    "development_type",
    "agreement_type",
    "original_construction_period",
    "first_spa_date",
    "teduh_spa_price_min",
    "teduh_spa_price_max",
    "hims_project_reference_date",
    "hims_project_reference_date_basis",
    "hims_eligibility_cutoff_date",
    "reported_total_units",
    "unit_records_count",
    "sold_units",
    "unsold_units",
    "sales_percentage",
    "value_sold_percentage",
    "sales_construction_gap",
    "construction_percentage",
    "potential_listed_gdv",
    "sold_listed_value",
    "recorded_spa_sales_value",
    "estimated_sold_value",
    "remaining_listed_value",
    "recorded_price_realisation_percentage",
    "median_recorded_discount_percentage",
    "bumi_total_units",
    "bumi_sold_units",
    "bumi_unsold_units",
    "bumi_sales_percentage",
    "unit_coverage_percentage",
    "listed_price_coverage_percentage",
    "spa_price_coverage_percentage",
    "gdv_confidence",
    "sales_percentage_confidence",
    "sales_value_confidence",
    "construction_confidence",
    "permit_number",
    "permit_start_date",
    "permit_end_date",
    "expected_vp_date",
    "vp_period_amended",
    "approved_extension_period",
    "revised_construction_period",
    "revised_vp_date",
    "ccc_obtained",
    "ccc_date",
    "vp_date",
    "component_sales_count",
    "component_sales_confidence",
    "source_url",
    "source_detail_api_url",
    "source_units_api_url",
    "comparison_notes",
]


MANUAL_FIELD_SPECS: list[tuple[str, str]] = [
    ("region", "VARCHAR"),
    ("display_name", "VARCHAR"),
    ("parent_group", "VARCHAR"),
    ("project_set", "VARCHAR"),
    ("manual_launch_date", "DATE"),
    ("manual_built_up_min_sqft", "DECIMAL(16,2)"),
    ("manual_built_up_max_sqft", "DECIMAL(16,2)"),
    ("manual_psf_min", "DECIMAL(16,2)"),
    ("manual_psf_max", "DECIMAL(16,2)"),
    ("tracking_notes", "VARCHAR"),
    ("shortlist_active", "VARCHAR"),
    ("shortlist_origin", "VARCHAR"),
    ("project_scale_band", "VARCHAR"),
    ("commercial_scope", "VARCHAR"),
    ("commercial_scope_reason", "VARCHAR"),
]
SHORTLIST_FIELD_SPECS = MANUAL_FIELD_SPECS + FIELD_SPECS
SHORTLIST_FIELDS = [name for name, _ in SHORTLIST_FIELD_SPECS]
ALERT_FIELDS = [
    "snapshot_date",
    "region",
    "severity",
    "alert_code",
    "source_project_id",
    "display_name",
    "message",
]
