[theme]
base = "light"
primaryColor = "#E30613"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F6"
textColor = "#363B40"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
